server:
  port: 17017
  servlet:
    context-path: /oilgas
spring:
  application:
    name: oilgas_control
  datasource:
    master:
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://rm-w5g34aa7cn0e292b1.mysql.rds.ops-sgmc.sd.sgcc.com.cn:3306/middleground_busi?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowMultiQueries=true
      username: dwzyywzt
      password: Admin@123
      maxActive: 10
      #配置获取链接等待超时时间
      maxWait: 1000
      #配置间隔多久进行一次检测，检测需要关闭的空闲链接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      #配置一个链接在池中最小的生存时间，单位是毫秒
      minEvictableIdleTimeMillis: 60000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      #关键配置（每次获取链接后执行validationQuery，一定会降低性能，为了规避上述问题需配置）
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache,并且制定每个链接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 10
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，wall用于防火墙
      filters: stat
      userGlobalDataSourceStat: true
      #通过connectionProperties属性来打开margeSwql功能，慢sql记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
      #使用非公平锁（重要，减少竞争等待时间）
      useUnfairLock: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: false
      #原本的值
      #logAbandoned: true
      #最好配置，不然可能出现长达15分钟的校验时间，导致整个查询超时
      validationQueryTimeout: 1
      #在小于minIdel连接数的时候执行保活操作，防止防火墙断开连接
      minIdle: 5
      keepAlive: true
    core:
      driverClassName: oracle.jdbc.driver.OracleDriver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:oracle:thin:@10.140.247.41:11521:dwzydb3
      username: pms_psr      #用户名
      password: Pms+-2020      #密码
      maxActive: 20
      #配置获取链接等待超时时间
      maxWait: 1000
      #配置间隔多久进行一次检测，检测需要关闭的空闲链接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      #配置一个链接在池中最小的生存时间，单位是毫秒
      minEvictableIdleTimeMillis: 60000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      #关键配置（每次获取链接后执行validationQuery，一定会降低性能，为了规避上述问题需配置）
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache,并且制定每个链接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 30
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，wall用于防火墙
      filters: stat
      userGlobalDataSourceStat: true
      #通过connectionProperties属性来打开margeSwql功能，慢sql记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
      #使用非公平锁（重要，减少竞争等待时间）
      useUnfairLock: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      #最好配置，不然可能出现长达15分钟的校验时间，导致整个查询超时
      validationQueryTimeout: 1
      #在小于minIdel连接数的时候执行保活操作，防止防火墙断开连接
      minIdle: 10
      keepAlive: true
#mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations: classpath*:mybatis/**/*.xml
  type-aliases-package: com.oilgas.po    # 所有Entity别名类所在包

logging:
  file:
    name: oilgas_control
    path: ./logs
    max-history: 7
    max-size: 10MB
  level:
    root: info
  config: classpath:logback-spring.xml
########## 将服务注册到eureka 的配置##################
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:5607/eureka/
    #定时刷新本地实例的信息，缺省：30秒
    #instance-info-replication-interval-seconds: 30
  instance:
    #服务实例的主机名称
    #hostname: 127.0.0.1
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    instanceid: ${spring.cloud.client.ipAddress}:${server.port}

# pageHelper 配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

cron: 0 30 0 * * ?